name: Deploy Frontend (Next.js)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/madeireira-erp/REI-FRONT
            git reset --hard origin/main
            git pull origin main
            
            npm install
            # Build do Next.js (Cuidado com a memória RAM da VPS aqui)
            npm run build
            
            pm2 restart rei-front || pm2 start npm --name "rei-front" -- start -- -p 3001
            pm2 save